version: "3.8"

services:
  ros:
    container_name: ros
    build:
      context: .
      dockerfile: Dockerfile
    image: ros:latest
    user: ubuntu
    environment:
      - DISPLAY
      - XAUTHORITY
    volumes:
      - ..:/project
    working_dir: /project
    privileged: true
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash"]
